os: linux
dist: focal
group: stable

language: generic

cache:
  directories:
    - vendor

branches:
  only:
    - master

services:
  - docker

before_script:
  - chmod +x bin/travis_ci_before_script.sh
  - ./bin/travis_ci_before_script.sh
