os: linux
dist: bionic
sudo: required
group: edge

language: php
php:
  - '8.0'

cache:
  directories:
    - vendor

branches:
  only:
    - master

services:
  - redis

before_script:
  - sudo apt-get install php-redis
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.in
  - chmod +x bin/travis_ci_before_script.sh
  - ./bin/travis_ci_before_script.sh

script:
  - vendor/bin/phpunit
