os: linux
dist: focal
sudo: required
group: stable

language: generic

cache:
  directories:
    - vendor

branches:
  only:
    - master

before_script:
  - sudo apt install lsb-release ca-certificates apt-transport-https software-properties-common -y
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt update
  - sudo apt install -y php8.0
  - sudo apt-get install php8.0-redis
  - composer install
